[package]
name = "templates"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.1"
askama_actix = "0.14.0"

entity = { path = "../entity" }
